# SEO settings
title: "/param/"
title2: "home" # default: ""
# description: "Just another minimalist Jekyll theme that focuses on technical writing."
# keywords: "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url: https://param.codes# site url
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

repo: http://github.com/heiswayi/thinkspace
# disqus_shortname: "heiswayi"
twitter_username: "iliekcomputers"
# comments: true

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name: "Param Singh"
  job: "Software Engineer at Stripe"
  bio: "I write code, listen to music, play chess and reddit. This is my place on the web."
  thumb: /images/author.jpg
  email: paramsingh258@gmail.com
  url: http://paramsingh.github.io
  github: http://github.com/paramsingh
  twitter: http://twitter.com/iliekcomputers
  facebook: https://www.facebook.com/prmsngh
  linkedin: http://linkedin.com/in/prmsngh

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "iliekcomputers"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: blog
    title: Blog

exclude:
  [
    "gulp",
    "node_modules",
    "bower",
    "bower_components",
    "config.rb",
    "src",
    "Gemfile",
    "Gemfile.lock",
    ".rvmrc",
    ".rbenv-version",
    "package.json",
    "gulpfile.js",
    "README.md",
    "Rakefile",
    "changelog.md",
  ]
